name: Ubuntu Server

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Installing SSH
      run: |
        sudo apt-get update
        sudo apt-get install -y ssh

    - name: Setting up SSH
      run: |
        echo "PermitRootLogin yes" | sudo tee -a /etc/ssh/sshd_config
        sudo service ssh restart

    - name: Setting up ngrok
      run: |
        wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
        unzip ngrok-stable-linux-amd64.zip
        chmod +x ./ngrok

    - name: Connect to ngrok
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      run: ./ngrok authtoken $NGROK_AUTH_TOKEN

    - name: Create ngrok tunnel
      run: |
        ./ngrok tcp 22 &

    - name: Display ngrok public address
      run: |
        sleep 5
        curl http://localhost:4040/api/tunnels
