name: Ubuntu Machine Setup

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ngrok
      run: |
        wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
        unzip ngrok-stable-linux-amd64.zip
        chmod +x ngrok
        ./ngrok authtoken <YOUR_NGROK_AUTH_TOKEN>
        ./ngrok http 80 &

    - name: Set up Ubuntu machine
      run: |
        sudo apt update
        sudo apt install -y ubuntu-desktop
        sudo ufw allow 22
        sudo ufw enable
        sudo apt install -y git
        git clone <YOUR_GITHUB_REPOSITORY_URL>
        # Set up your application
        # Start your application
